routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('employee.home');
})->name('home');

Route::get('/checklist', function () {
    return view('employee.checklists.checklist');
})->name('employee.check');

Route::prefix('employee')->group(function () {
    Route::resource('/request', 'RequestController');
    Route::get('/checklist/{model}', 'ChecklistController@new')->name('checklist.new');
    Route::resource('/checklist', 'ChecklistController');
});

app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    protected $table = 'employees';

    public function checklists(){
        return $this->hasMany(Checklist::class);
    }

    public function user(){
        return $this->hasOne(User::class);
    }

    public function requests(){
        return $this->hasMany(Request::class);
    }

}

app/Request.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Request extends Model
{
    protected $table = 'requests';

    public function employee(){
        return $this->belongsTo(Employee::class);
    }

    public function request_criticality(){
        return $this->belongsTo(RequestCriticality::class);
    }

    public function request_status(){
        return $this->belongsTo(RequestStatus::class);
    }

    public function equipment(){
        return $this->belongsTo(Equipment::class);
    }

    public function plan(){
        return $this->belongsTo(Plan::class);
    }

    public function getDateAttribute()
    {
        return date('d/m/Y', strtotime($this->attributes['date']));
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Employee;
use Illuminate\Http\Request;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function show(Employee $employee)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function edit(Employee $employee)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Employee $employee)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function destroy(Employee $employee)
    {
        //
    }
}

app/Http/Controllers/RequestController.php
<?php

namespace App\Http\Controllers;

use App\Request as EmployeeRequest;
use Illuminate\Http\Request;
use App\User;
use App\RequestCriticality;
use App\RequestStatus;
use App\Equipment;
use App\Plan;

class RequestController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('employee.requests.list_requests');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('employee.requests.new_request');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $employee_request = new EmployeeRequest;
        //MUDAR
        $employee_request->employee_id = User::find(2)->employee()->first()->id;
        $employee_request->request_criticality_id = RequestCriticality::find($request->criticality)->id;
        $employee_request->equipment_id = Equipment::find($request->equipment)->id;
        $employee_request->request_status_id = RequestStatus::where('slug', 'aberto')->first()->id;

        if(isset($request->plan)){
            $employee_request->plan_id = Plan::find($request->plan)->id;
        }

        $employee_request->date = date('Y-m-d');
        $employee_request->reference = $request->reference;
        $employee_request->position = $request->position;
        $employee_request->observations = $request->obs;
        $employee_request->description = $request->description;

        $employee_request->save();

        return redirect()->route('home');
    }

    /**
     * Display the specified resource.
     *
     * @param  EmployeeRequest  $employee_request
     * @return \Illuminate\Http\Response
     */
    public function show(EmployeeRequest $employee_request)
    {
        echo json_encode($employee_request);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  EmployeeRequest  $employee_request
     * @return \Illuminate\Http\Response
     */
    public function edit(EmployeeRequest $employee_request)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  EmployeeRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, EmployeeRequest $employee_request)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  EmployeeRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function destroy(EmployeeRequest $employee_request)
    {
        //
    }
}

resources/views/employee/requests/list_requests.blade.php
@php
    use App\Request;

    $requests = Request::where('employee_id', 2)->get();
@endphp

@extends('employee.templates.employee_menu')

@section('content')
    <div class="row center">
        <div class="container">
            <div class="row">
                <h4>Suas solicitações</h4>
            </div>
            <div class="row">
                <div class="card">
                    <table class="centered">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Data</th>
                                <th>Ativo</th>
                                <th>Plano</th>
                                <th>Posição</th>
                                <th>Referência</th>
                                <th>Status</th>
                                <th>Criticidade</th>
                            </tr>
                        </thead>

                        <tbody>
                            @foreach ($requests as $request)
                                <tr>
                                    <td>{{ $request->id }}</td>
                                    <td>{{ $request->date }}</td>
                                    <td>{{ $request->equipment()->first()->reg }}</td>
                                    <td>{{ $request->plan()->first()->name }}</td>
                                    <td>{{ $request->position }}</td>
                                    <td>{{ $request->reference }}</td>
                                    <td>{{ $request->request_status()->first()->name }}</td>
                                    <td>{{ $request->request_criticality()->first()->name }}</td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        $(document).ready(function(){

            $('.modal').modal();
        });
    </script>
@endsection

resources/views/employee/requests/new_request.blade.php
@php
    use App\Equipment;
    use App\Plan;
    use App\RequestCriticality;

    $equipments = Equipment::all();
    $plans = Plan::all();
    $criticalities = RequestCriticality::all();
@endphp

@extends('employee.templates.employee_menu')

@section('content')
    <div class="row center">
        <div class="container">
            <div class="row center">
                <h4>Nova solicitação</h4>
            </div>
            <div class="row">
                <form class="col s12" action="{{ route('request.store') }}" method="post">
                    @csrf
                    <div class="row">
                        <div class="input-field col l2">
                            <input id="date" type="text" class="datepicker" value="{{date('d/m/Y')}}" name="date">
                            <label for="date">Data da solicitação</label>
                        </div>
                        <div class="input-field col l3">
                            <input disabled id="user" type="text" class="validate" value="*usuario logado*" name="user">
                            <label for="user">Usuário</label>
                        </div>
                    </div>
                    <div class="divider"></div>
                    <div class="row">
                        <div class="input-field col l4">
                            <select name="equipment">
                                <option value="" disabled selected>Ativo</option>
                                @foreach ($equipments as $equipment)
                                    <option value="{{ $equipment->id }}">{{ $equipment->reg }} - {{ $equipment->equipment_model()->first()->name }}</option>
                                @endforeach
                            </select>
                            <label>Ativo</label>
                        </div>
                        <div class="input-field col l4">
                            <select name="plan">
                                <option value="" disabled selected>Selecione se houver</option>
                                @foreach ($plans as $plan)
                                    <option value="{{ $plan->id }}">{{ $plan->name }}</option>
                                @endforeach
                            </select>
                            <label>Plano</label>
                        </div>
                        <div class="input-field col l4">
                            <select name="criticality">
                                <option value="" disabled selected>Criticidade</option>
                                @foreach ($criticalities as $criticality)
                                    <option value="{{ $criticality->id }}">{{ $criticality->name }}</option>
                                @endforeach
                            </select>
                            <label>Criticidade</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col l3">
                            <input id="position" type="text" class="validate" name="position">
                            <label for="position">Posição</label>
                        </div>
                        <div class="input-field col l3">
                            <input id="reference" type="text" class="validate" name="reference">
                            <label for="reference">Referência</label>
                        </div>
                        <div class="input-field col l6">
                            <textarea id="obs" class="materialize-textarea" data-length="255" name="obs"></textarea>
                            <label for="obs">Observações</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col l6">
                            <textarea id="description" class="materialize-textarea" data-length="255" name="description"></textarea>
                            <label for="description">Descrição</label>
                        </div>
                    </div>
                    <div class="row">
                        <button type="submit" class="btn">Cadastrar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        $(document).ready(function(){
            $('select').formSelect();

            $('textarea#obs, textarea#description').characterCounter();
        });
    </script>
@endsection